#!/usr/bin/env bash
# Validate that every commit introduced by a pull request uses Conventional
# Commits. The changelog is generated from these subjects, so a commit that
# does not parse is a commit that silently disappears from the release notes.
#
# Usage: check-conventional-commits.sh <base-sha> <head-sha>
set -euo pipefail

BASE="${1:?base sha required}"
HEAD="${2:?head sha required}"

TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
# type(optional scope)!: summary   — summary must be non-empty and lowercase-ish
PATTERN="^(${TYPES})(\([a-z0-9._/-]+\))?!?: .+"

fail=0
count=0

# Merge commits are generated by GitHub, not written by a human — skip them.
while IFS= read -r sha; do
  [ -z "$sha" ] && continue
  subject=$(git log -1 --format=%s "$sha")
  count=$((count + 1))

  if [[ "$subject" =~ $PATTERN ]]; then
    if [ "${#subject}" -gt 72 ]; then
      echo "  ! ${sha:0:8}  subject is ${#subject} chars (soft limit 72)"
      echo "      $subject"
    else
      echo "  ok ${sha:0:8}  $subject"
    fi
  else
    echo "  x  ${sha:0:8}  $subject"
    fail=1
  fi
done < <(git rev-list --no-merges "${BASE}..${HEAD}")

if [ "$count" -eq 0 ]; then
  echo "No non-merge commits in range; nothing to validate."
  exit 0
fi

if [ "$fail" -ne 0 ]; then
  cat <<'MSG'

Some commit subjects are not Conventional Commits.

  <type>(<optional scope>): <summary in the imperative>

  types: feat fix docs style refactor perf test build ci chore revert
  breaking: append ! after the type, or add a BREAKING CHANGE: footer

  good:  feat(log): accept workouts pasted as free text
         fix(auth): stop refreshing an expired session on the server
  bad:   Update  |  changes  |  deployable  |  fixed stuff

Rewrite them with:  git rebase -i <base>   (reword the offending commits)
MSG
  exit 1
fi

echo ""
echo "All $count commit(s) are Conventional Commits."
